name: get_cli_dempster_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  lottie: 1.3.0
  flutter_svg: 1.0.3
  intl: 0.17.0
  font_awesome_flutter: 10.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/icons/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Muli
      fonts: 
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
  uses-material-design: true

